# -*- coding: utf-8 -*-
{
    'name': 'Spa & Wellness Management',
    'version': '19.0.1.0.0',
    'category': 'Services/Spa',
    'summary': 'Complete Spa & Wellness ERP: Appointments, Therapists, Rooms, Commissions, Memberships',
    'author': 'Your Company',
    'depends': [
        'base', 'mail', 'calendar', 'sale_management',
        'account', 'stock', 'hr', 'hr_holidays',
        'point_of_sale', 'sms',
    ],
    'data': [
        'security/spa_security.xml',
        'security/ir.model.access.csv',
        'data/spa_sequence_data.xml',
        'data/spa_mail_template.xml',
        'views/spa_service_views.xml',
        'views/spa_room_views.xml',
        'views/spa_therapist_views.xml',
        'views/spa_appointment_views.xml',
        'views/spa_therapist_commission_views.xml',
        'views/spa_service_category.xml',
        'views/spa_report_views.xml',
        'report/sap_appointment_action.xml',
        'report/spa_appointment_report.xml',
        'views/spa_membership_views.xml',
        'views/spa_package_views.xml',
        'views/spa_membership_plan_views.xml',
        'views/spa_menu_views.xml',

    ],

    'assets': {
        'web.assets_backend': [
            'spa_wellness/static/src/js/spa_dashboard.js',
            'spa_wellness/static/src/js/commision_rep.js',
            'spa_wellness/static/src/js/appointment_rep.js',
            'spa_wellness/static/src/js/spa_slot_checker.js',
            'spa_wellness/static/src/js/spa_membership_plans.js',
            'spa_wellness/static/src/js/spa_packages.js',
            'spa_wellness/static/src/js/spa_rooms.js',
            'spa_wellness/static/src/js/spa_therapists.js',
            'spa_wellness/static/src/js/spa_services.js',
            'spa_wellness/static/src/js/spa_booking_panel.js',
            'spa_wellness/static/src/js/spa_appointment_cards.js',
            'spa_wellness/static/src/xml/spa_dashboard.xml',
            'spa_wellness/static/src/xml/commision_rep.xml',
            'spa_wellness/static/src/xml/appointment_rep.xml',
            'spa_wellness/static/src/xml/spa_slot_checker.xml',
            'spa_wellness/static/src/xml/spa_membership_plans.xml',
            'spa_wellness/static/src/xml/spa_packages.xml',
            'spa_wellness/static/src/xml/spa_rooms.xml',
            'spa_wellness/static/src/xml/spa_therapists.xml',
            'spa_wellness/static/src/xml/spa_services.xml',
            'spa_wellness/static/src/xml/spa_booking_panel.xml',
            'spa_wellness/static/src/xml/spa_appointment_cards.xml',
            'spa_wellness/static/src/css/spa_dashboard.css',
            'spa_wellness/static/src/css/spa_booking_panel.css',

        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}